<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <PackageId>WodiLib</PackageId>
        <PackageVersion>2.3.65534.39</PackageVersion>
        <Copyright>Copyright 2019 kameske</Copyright>
        <Version>2.3.65534.39</Version>
        <PackageProjectUrl>https://github.com/kameske/WodiLib</PackageProjectUrl>
        <PackageLicenseUrl/>
        <RepositoryUrl>https://github.com/kameske/WodiLib.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <Title>WodiLib</Title>
        <Authors>Kameske</Authors>
        <RootNamespace>WodiLib</RootNamespace>
        <Product>WodiLib</Product>
        <AssemblyVersion>2.3.65534.39</AssemblyVersion>
        <AssemblyName>WodiLib</AssemblyName>
        <LangVersion>9</LangVersion>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <!--    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>-->
        <!--    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>-->
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\WodiLib.xml</DocumentationFile>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DocumentationFile>bin\Release\WodiLib.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0"/>
        <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0"/>
        <PackageReference Include="System.Text.Encoding.CodePages" Version="4.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WodiLib.SourceGenerator\WodiLib.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <!--    <Compile Remove="Generated\**\*.cs" />-->
        <Compile Remove="Common\**"/>
        <Compile Remove="Database\**"/>
        <Compile Remove="Event\**"/>
        <Compile Remove="Map\**"/>
        <Compile Remove="Project\**"/>
        <Compile Remove="Cmn\VariableAddress\**"/>
        <Compile Remove="IO\**"/>
        <Compile Remove="Ini\**"/>
        <Compile Remove="Cmn\**" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Event\EventCommand\Implement\_EventCommandCodeImplementTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_EventCommandCodeImplementTemplate.cs</LastGenOutput>
        </None>
        <None Update="Event\EventCommand\Implement\_EventCommandItemEqualsMethodImplementTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_EventCommandItemEqualsMethodImplementTemplate.cs</LastGenOutput>
        </None>
        <None Update="Event\EventCommand\Implement\_EventCommandNoArgsTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_EventCommandNoArgsTemplate.cs</LastGenOutput>
        </None>
        <None Update="Event\CharaMoveCommand\Implement\_CharaMoveCommandItemEqualsMethodImplementTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_CharaMoveCommandItemEqualsMethodImplementTemplate.cs</LastGenOutput>
        </None>
        <None Update="Event\CharaMoveCommand\Implement\_CharaMoveCommandCodeImplementTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_CharaMoveCommandCodeImplementTemplate.cs</LastGenOutput>
        </None>
        <None Update="Event\CharaMoveCommand\Implement\_CharaMoveCommandNoCommandValuesImplementTemplate.tt">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>_CharaMoveCommandNoCommandValuesImplementTemplate.cs</LastGenOutput>
        </None>
        <None Remove="Common\**"/>
        <None Remove="Database\**"/>
        <None Remove="Event\**"/>
        <None Remove="Map\**"/>
        <None Remove="Project\**"/>
        <None Remove="Cmn\VariableAddress\**"/>
        <None Remove="IO\**"/>
        <None Remove="Ini\**"/>
        <None Remove="Cmn\**" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Common\**"/>
        <EmbeddedResource Remove="Database\**"/>
        <EmbeddedResource Remove="Event\**"/>
        <EmbeddedResource Remove="Map\**"/>
        <EmbeddedResource Remove="Project\**"/>
        <EmbeddedResource Remove="Cmn\VariableAddress\**"/>
        <EmbeddedResource Remove="IO\**"/>
        <EmbeddedResource Remove="Ini\**"/>
        <EmbeddedResource Remove="Cmn\**" />
    </ItemGroup>
</Project>
