<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <IsPackable>false</IsPackable>

        <RootNamespace>WodiLib.Test</RootNamespace>

        <Nullable>enable</Nullable>

        <AssemblyName>WodiLib.Test</AssemblyName>

        <LangVersion>10</LangVersion>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
        <TargetFramework>net8.0</TargetFramework>

        <!-- SourceGenerator が出力するAttributeによって警告が発生するため抑制する -->
        <NoWarn>$(NoWarn);CS0436</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="nunit" Version="3.12.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="3.17.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WodiLib.SourceGenerator\WodiLib.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\WodiLib\WodiLib.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="TestResources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>TestResources.resx</DependentUpon>
        </Compile>
        <Compile Remove="Generated\**\*.cs"/>
        <Compile Remove="Common\**"/>
        <Compile Remove="Event\**"/>
        <Compile Remove="Map\**"/>
        <Compile Remove="Project\**"/>
        <Compile Remove="Ini\**"/>
        <Compile Remove="IO\TestData\Common\**"/>
        <Compile Remove="IO\TestData\CommonEventDat\**"/>
        <Compile Remove="IO\TestData\Ini\**"/>
        <Compile Remove="IO\TestData\Mps\**"/>
        <Compile Remove="IO\CommonEventDataFileIOTest.cs"/>
        <Compile Remove="IO\CommonEventDataFileReaderTest.cs"/>
        <Compile Remove="IO\CommonEventDataFileWriterTest.cs"/>
        <Compile Remove="IO\CommonFileIOTest.cs"/>
        <Compile Remove="IO\CommonFileReaderTest.cs"/>
        <Compile Remove="IO\CommonFileWriterTest.cs"/>
        <Compile Remove="IO\EditorIniFileIOTest.cs"/>
        <Compile Remove="IO\EditorIniFileReaderTest.cs"/>
        <Compile Remove="IO\EditorIniFileWriterTest.cs"/>
        <Compile Remove="IO\GameIniFileIOTest.cs"/>
        <Compile Remove="IO\GameIniFileReaderTest.cs"/>
        <Compile Remove="IO\GameIniFileWriterTest.cs"/>
        <Compile Remove="IO\MapFileIOTest.cs"/>
        <Compile Remove="IO\MapFileReaderTest.cs"/>
        <Compile Remove="IO\MapFileWriterTest.cs"/>
        <Compile Remove="IO\MapTreeDataFileIOTest.cs"/>
        <Compile Remove="IO\MapTreeDataFileReaderTest.cs"/>
        <Compile Remove="IO\MapTreeDataFileWriterTest.cs"/>
        <Compile Remove="IO\MapTreeOpenStatusDataFileIOTest.cs"/>
        <Compile Remove="IO\MapTreeOpenStatusDataFileReaderTest.cs"/>
        <Compile Remove="IO\MapTreeOpenStatusDataFileWriterTest.cs"/>
        <Compile Remove="IO\TileSetDataFileIOTest.cs"/>
        <Compile Remove="IO\TileSetDataFileReaderTest.cs"/>
        <Compile Remove="IO\TileSetDataFileWriterTest.cs"/>
        <Compile Remove="IO\TileSetFileIOTest.cs"/>
        <Compile Remove="IO\TileSetFileReaderTest.cs"/>
        <Compile Remove="IO\TileSetFileWriterTest.cs"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="TestResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>TestResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Remove="Common\**"/>
        <EmbeddedResource Remove="Event\**"/>
        <EmbeddedResource Remove="Map\**"/>
        <EmbeddedResource Remove="Project\**"/>
        <EmbeddedResource Remove="Ini\**"/>
        <EmbeddedResource Remove="IO\TestData\Common\**"/>
        <EmbeddedResource Remove="IO\TestData\CommonEventDat\**"/>
        <EmbeddedResource Remove="IO\TestData\Ini\**"/>
        <EmbeddedResource Remove="IO\TestData\Mps\**"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Commons.Convertible, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>..\lib\Commons.Convertible\Commons.Convertible.dll</HintPath>
        </Reference>
        <Reference Include="Commons.DIContainer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>..\lib\Commons.DIContainer\Commons.DIContainer.dll</HintPath>
        </Reference>
        <Reference Include="Commons.Linq.Extension, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>..\lib\Commons.Linq.Extension\Commons.Linq.Extension.dll</HintPath>
        </Reference>
        <Reference Include="Commons.Logger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>..\lib\Commons.Logger\Commons.Logger.dll</HintPath>
        </Reference>
        <Reference Include="Commons.TypeSafeEnum, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>..\lib\Commons.TypeSafeEnum\Commons.TypeSafeEnum.dll</HintPath>
        </Reference>
        <Reference Include="Commons.Validator">
            <HintPath>..\lib\Commons.Validator\Commons.Validator.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Common\**"/>
        <None Remove="Event\**"/>
        <None Remove="Ini\**"/>
        <None Remove="IO\TestData\Common\**"/>
        <None Remove="IO\TestData\CommonEventDat\**"/>
        <None Remove="IO\TestData\Ini\**"/>
        <None Remove="IO\TestData\Mps\**"/>
        <None Remove="Map\**"/>
        <None Remove="Project\**"/>
    </ItemGroup>

</Project>
