// ========================================
// Project Name : WodiLib.SourceGenerator
// File Name    : TwoDListGeneratorBase.BuildRestrictedClassSource.cs
//
// MIT License Copyright(c) 2019 kameske
// see LICENSE file
// ========================================

using System.Linq;
using WodiLib.SourceGenerator.Core.SourceBuilder;
using WodiLib.SourceGenerator.ValueObject.Extensions;
using static WodiLib.SourceGenerator.Core.SourceBuilder.SourceConstants;

namespace WodiLib.SourceGenerator.Domain.Collection.Generation.Main.Common
{
    internal abstract partial class TwoDListGeneratorBase
    {
        private static SourceFormatTargetBlock BuildRestrictedClassSource(ModelInformation modelInfo)
        {
            return SourceTextFormatter.Format(
                "",
                // -----
                // class start
                new[]
                {
                    $"/// <summary>",
                    $"/// {__}{modelInfo.Description}",
                    $"/// </summary>",
                    $"{modelInfo.Accessibility} {modelInfo.AbstractKeyword}partial class {modelInfo.RestrictedCapacityListInfo.RestrictedCapacityListClassName} : {modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword},",
                    $"{__}WodiLib.Sys.IDeepCloneable<{modelInfo.RestrictedCapacityListInfo.RestrictedCapacityListClassNameWithoutInOutKeyword}>",
                    $"{{",
                },
                // Properties
                BuildRestrictedCapacityListClassSettingsInterfaceImplementsSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // Constructors
                BuildRestrictedCapacityListConstructorSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // Methods
                BuildRestrictedCapacityListMethodsSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // DeepClone
                BuildRestrictedCapacityListDeepCloneSource(modelInfo),
                // class end
                new[]
                {
                    $"}}",
                }
            );
        }

        private static SourceFormatTargetBlock BuildRestrictedCapacityListClassSettingsInterfaceImplementsSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                modelInfo.Members.RestrictedListProperties.SelectMany(p => p.ImplementationCode).ToArray()
            );
        }

        private static SourceFormatTargetBlock BuildRestrictedCapacityListConstructorSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                $"public {modelInfo.RestrictedCapacityListInfo.RestrictedCapacityListClassNameWithoutInOutKeyword}({modelInfo.SettingsInterfaceInfo.SettingsInterfaceNameWithoutIOKeyword} settings) : base(settings) {{ }}",
                $"",
                $"private protected {modelInfo.RestrictedCapacityListInfo.RestrictedCapacityListClassNameWithoutInOutKeyword}({modelInfo.SettingsInterfaceInfo.SettingsInterfaceNameWithoutIOKeyword} settings, SimpleList<{modelInfo.RowType}> itemsImpl) : base(settings, itemsImpl) {{ }}",
                $"",
                modelInfo.Members.RestrictedListConstructors.SelectMany(p => p.ImplementationCode).ToArray()
            );
        }

        private static SourceFormatTargetBlock BuildRestrictedCapacityListMethodsSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                modelInfo.Members.RestrictedListMethods.SelectMany(p => p.ImplementationCode).ToArray(),
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの末尾に{modelInfo.RowLogicalName}要素を追加する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">追加する{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public {modelInfo.FixedLengthRowType} Add{modelInfo.RowPhysicalName}({modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.AddRow(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの末尾に{modelInfo.RowLogicalName}要素を追加する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">追加する{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Add{modelInfo.RowPhysicalName}Range(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.AddRowRange(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスの位置に{modelInfo.RowLogicalName}要素を挿入する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">追加する{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public {modelInfo.FixedLengthRowType} Insert{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.InsertRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスの位置に{modelInfo.RowLogicalName}要素を挿入する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">追加する{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Insert{modelInfo.RowPhysicalName}Range(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.InsertRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスを起点として、{modelInfo.RowLogicalName}要素の上書き/追加を行う。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">上書き/追加{modelInfo.RowLogicalName}リスト</param>",
                $"/// <returns>上書きした{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Overwrite{modelInfo.RowPhysicalName}(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.OverwriteRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスの{modelInfo.RowLogicalName}要素を削除する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <returns>削除した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/> を下回る場合。",
                $"/// </exception>",
                $"public {modelInfo.FixedLengthRowType} Remove{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index) => Table.RemoveRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.RowLogicalName}要素の範囲を削除する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"count\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>)] 削除する{modelInfo.RowLogicalName}数</param>",
                $"/// <returns>削除した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>, <paramref name=\"count\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.RowLogicalName}要素を削除しようとした場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/> を下回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Remove{modelInfo.RowPhysicalName}Range(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.RemoveRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.RowLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.RowLogicalName}数",
                $"/// </param>",
                $"/// <returns>追加または削除した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Adjust{modelInfo.RowPhysicalName}Length(int length)",
                $"{__}=> Table.AdjustRowLength(length);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.RowLogicalName}数が不足している場合、{modelInfo.RowLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.RowLogicalName}数",
                $"/// </param>",
                $"/// <returns>追加した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Adjust{modelInfo.RowPhysicalName}LengthIfShort(int length)",
                $"{__}=> Table.AdjustRowLengthIfShort(length);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.RowLogicalName}数が超過している場合、{modelInfo.RowLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.RowLogicalName}数",
                $"/// </param>",
                $"/// <returns>削除した{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Adjust{modelInfo.RowPhysicalName}LengthIfLong(int length)",
                $"{__}=> Table.AdjustRowLengthIfLong(length);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの末尾に{modelInfo.ColumnLogicalName}要素を追加する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">追加する{modelInfo.ColumnLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.ElementType}> Add{modelInfo.ColumnPhysicalName}(IEnumerable<{modelInfo.ElementSettingsType}> settings) => Table.AddColumn(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの末尾に{modelInfo.ColumnLogicalName}要素を追加する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">追加する{modelInfo.ColumnLogicalName}要素（外側のIEnumerableが{modelInfo.ColumnLogicalName}、内側のIEnumerableが各{modelInfo.ColumnLogicalName}の{modelInfo.RowLogicalName}要素）</param>",
                $"/// <returns>追加した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Add{modelInfo.ColumnPhysicalName}Range(",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.AddColumnRange(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスの位置に{modelInfo.ColumnLogicalName}要素を挿入する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/>)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">追加する{modelInfo.ColumnLogicalName}要素</param>",
                $"/// <returns>追加した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.ElementType}> Insert{modelInfo.ColumnPhysicalName}(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.ElementSettingsType}> settings",
                $") => Table.InsertColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスの位置に{modelInfo.ColumnLogicalName}要素を挿入する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/>)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">追加する{modelInfo.ColumnLogicalName}要素（外側のIEnumerableが{modelInfo.ColumnLogicalName}、内側のIEnumerableが各{modelInfo.ColumnLogicalName}の{modelInfo.RowLogicalName}要素）</param>",
                $"/// <returns>追加した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Insert{modelInfo.ColumnPhysicalName}Range(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.InsertColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスを起点として、{modelInfo.ColumnLogicalName}要素の上書き/追加を行う。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/>)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">上書き/追加{modelInfo.ColumnLogicalName}リスト（外側のIEnumerableが{modelInfo.ColumnLogicalName}、内側のIEnumerableが各{modelInfo.ColumnLogicalName}の{modelInfo.RowLogicalName}要素）</param>",
                $"/// <returns>上書きした{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を上回る場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Overwrite{modelInfo.ColumnPhysicalName}(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.OverwriteColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスの{modelInfo.ColumnLogicalName}要素を削除する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <returns>削除した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/> を下回る場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.ElementType}> Remove{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.RemoveColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.ColumnLogicalName}要素の範囲を削除する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"count\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/>)] 削除する{modelInfo.ColumnLogicalName}数</param>",
                $"/// <returns>削除した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/>, <paramref name=\"count\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.ColumnLogicalName}要素を削除しようとした場合。",
                $"/// </exception>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}操作によって{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/> を下回る場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Remove{modelInfo.ColumnPhysicalName}Range(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.RemoveColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.ColumnLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.ColumnLogicalName}数",
                $"/// </param>",
                $"/// <returns>追加または削除した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Adjust{modelInfo.ColumnPhysicalName}Length(int length) => Table.AdjustColumnLength(length);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.ColumnLogicalName}数が不足している場合、{modelInfo.ColumnLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.ColumnLogicalName}数",
                $"/// </param>",
                $"/// <returns>追加した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Adjust{modelInfo.ColumnPhysicalName}LengthIfShort(int length)",
                $"{__}=> Table.AdjustColumnLengthIfShort(length);",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.ColumnLogicalName}数が超過している場合、{modelInfo.ColumnLogicalName}数を指定の数に合わせる。",
                $"/// </summary>",
                $"/// <param name=\"length\">",
                $"/// {__}[Range(<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/>,",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/>)]",
                $"/// {__}調整する{modelInfo.ColumnLogicalName}数",
                $"/// </param>",
                $"/// <returns>削除した{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"length\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Adjust{modelInfo.ColumnPhysicalName}LengthIfLong(int length)",
                $"{__}=> Table.AdjustColumnLengthIfLong(length);",
                $"",
                $"/// <summary>",
                $"/// {__}要素を与えられた内容で一新する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">二次元リストに詰め直す要素</param>",
                $"/// <returns>新たに二次元リストに詰め直した要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}<paramref name=\"settings\"/> の{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/> 未満",
                $"/// {__}または <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> を超える場合、",
                $"/// {__}{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/> 未満",
                $"/// {__}または <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> を超える場合。",
                $"/// </exception>",
                $"/// <remarks>",
                $"/// {__}このメソッドは <paramref name=\"settings\"/> の{modelInfo.RowLogicalName}数が",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.RowPhysicalName}Capacity\"/> 以上",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.RowPhysicalName}Capacity\"/> 以下、",
                $"/// {__}{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMin{modelInfo.ColumnPhysicalName}Capacity\"/> 以上",
                $"/// {__}<see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.GetMax{modelInfo.ColumnPhysicalName}Capacity\"/> 以下であれば",
                $"/// {__}成功する。<br/>",
                $"/// {__}現在の{modelInfo.RowLogicalName}数・{modelInfo.ColumnLogicalName}数と一致しない場合エラーとしたい場合は、",
                $"/// {__}容量固定型にキャストしてから同メソッドを呼び出す。",
                $"/// </remarks>",
                $"public new IEnumerable<{modelInfo.FixedLengthRowType}> Reset(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.Reset(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}自身を初期化する。",
                $"/// </summary>",
                $"public void Clear() => Table.Clear();",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateAdd{modelInfo.RowPhysicalName}({modelInfo.RowSettingsType} settings) => Table.ValidateAddRow(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.RowPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.RowPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateAdd{modelInfo.RowPhysicalName}Range(IEnumerable<{modelInfo.RowSettingsType}> settings)",
                $"{__}=> Table.ValidateAddRowRange(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateInsert{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.ValidateInsertRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.RowPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.RowPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateInsert{modelInfo.RowPhysicalName}Range(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.RowSettingsType}> settings)",
                $"{__}=> Table.ValidateInsertRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Overwrite{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Overwrite{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateOverwrite{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.RowSettingsType}> settings)",
                $"{__}=> Table.ValidateOverwriteRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateRemove{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index) => Table.ValidateRemoveRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.RowPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.RowPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateRemove{modelInfo.RowPhysicalName}Range(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int count) => Table.ValidateRemoveRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}Length\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}LengthIfShort\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}LengthIfLong\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Adjust{modelInfo.RowPhysicalName}Length\" path=\"param|exception\"/>",
                $"public void ValidateAdjust{modelInfo.RowPhysicalName}Length(int length) => Table.ValidateAdjustRowLength(length);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateAdd{modelInfo.ColumnPhysicalName}(IEnumerable<{modelInfo.ElementSettingsType}> settings) => Table.ValidateAddColumn(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.ColumnPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.ColumnPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateAdd{modelInfo.ColumnPhysicalName}Range(IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings)",
                $"{__}=> Table.ValidateAddColumnRange(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateInsert{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.ElementSettingsType}> settings)",
                $"{__}=> Table.ValidateInsertColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.ColumnPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.ColumnPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateInsert{modelInfo.ColumnPhysicalName}Range(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings)",
                $"{__}=> Table.ValidateInsertColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Overwrite{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Overwrite{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateOverwrite{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings)",
                $"{__}=> Table.ValidateOverwriteColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateRemove{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.ValidateRemoveColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.ColumnPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.ColumnPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateRemove{modelInfo.ColumnPhysicalName}Range(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.ValidateRemoveColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}Length\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}LengthIfShort\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}LengthIfLong\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Adjust{modelInfo.ColumnPhysicalName}Length\" path=\"param|exception\"/>",
                $"public void ValidateAdjust{modelInfo.ColumnPhysicalName}Length(int length) => Table.ValidateAdjustColumnLength(length);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Clear\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Clear\" path=\"param|exception\"/>",
                $"public void ValidateClear() => Table.ValidateClear();",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.RowPhysicalName}\" path=\"param|returns\"/>",
                $"public {modelInfo.FixedLengthRowType} Add{modelInfo.RowPhysicalName}Internal({modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.AddRowInternal(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.RowPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.RowPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Add{modelInfo.RowPhysicalName}RangeInternal(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.AddRowRangeInternal(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.RowPhysicalName}\" path=\"param|returns\"/>",
                $"public {modelInfo.FixedLengthRowType} Insert{modelInfo.RowPhysicalName}Internal(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}{modelInfo.RowSettingsType} settings",
                $") => Table.InsertRowInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.RowPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.RowPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Insert{modelInfo.RowPhysicalName}RangeInternal(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.InsertRowRangeInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Overwrite{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Overwrite{modelInfo.RowPhysicalName}\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Overwrite{modelInfo.RowPhysicalName}Internal(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.OverwriteRowInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.RowPhysicalName}\" path=\"param|returns\"/>",
                $"public {modelInfo.FixedLengthRowType} Remove{modelInfo.RowPhysicalName}Internal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index) => Table.RemoveRowInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.RowPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.RowPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Remove{modelInfo.RowPhysicalName}RangeInternal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.RemoveRowRangeInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}Length\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}LengthIfShort\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.RowPhysicalName}LengthIfLong\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Adjust{modelInfo.RowPhysicalName}Length\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Adjust{modelInfo.RowPhysicalName}LengthInternal(int length)",
                $"{__}=> Table.AdjustRowLengthInternal(length);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.ColumnPhysicalName}\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.ElementType}> Add{modelInfo.ColumnPhysicalName}Internal(IEnumerable<{modelInfo.ElementSettingsType}> settings)",
                $"{__}=> Table.AddColumnInternal(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Add{modelInfo.ColumnPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Add{modelInfo.ColumnPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Add{modelInfo.ColumnPhysicalName}RangeInternal(",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.AddColumnRangeInternal(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.ColumnPhysicalName}\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.ElementType}> Insert{modelInfo.ColumnPhysicalName}Internal(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.ElementSettingsType}> settings",
                $") => Table.InsertColumnInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Insert{modelInfo.ColumnPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Insert{modelInfo.ColumnPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Insert{modelInfo.ColumnPhysicalName}RangeInternal(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.InsertColumnRangeInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Overwrite{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Overwrite{modelInfo.ColumnPhysicalName}\" path=\"param|returns\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Overwrite{modelInfo.ColumnPhysicalName}Internal(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.OverwriteColumnInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.ColumnPhysicalName}\" path=\"param|returns\"/>",
                $"public IEnumerable<{modelInfo.ElementType}> Remove{modelInfo.ColumnPhysicalName}Internal(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.RemoveColumnInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Remove{modelInfo.ColumnPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Remove{modelInfo.ColumnPhysicalName}Range\" path=\"param|returns\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Remove{modelInfo.ColumnPhysicalName}RangeInternal(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.RemoveColumnRangeInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}Length\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}LengthIfShort\"/>,",
                $"/// {__}<see cref=\"Adjust{modelInfo.ColumnPhysicalName}LengthIfLong\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Adjust{modelInfo.ColumnPhysicalName}Length\" path=\"param|returns\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Adjust{modelInfo.ColumnPhysicalName}LengthInternal(int length)",
                $"{__}=> Table.AdjustColumnLengthInternal(length);",
                $"",
                $"/// <inheritdoc",
                $"/// {__}cref=\"{modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword}.Reset(System.Collections.Generic.IEnumerable{{WodiLib.Test.Tools.{modelInfo.RowSettingsType}}})\"/>",
                $"public new IEnumerable<{modelInfo.FixedLengthRowType}> ResetInternal(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.ResetInternal(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Clear\"/> メソッド処理中核。",
                $"/// </summary>",
                $"public void ClearInternal() => Table.ClearInternal();"
            );
        }

        private static SourceFormatTargetBlock BuildRestrictedCapacityListDeepCloneSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                __,
                $"/// <inheritdoc/>",
                $"public new {modelInfo.RestrictedCapacityListInfo.RestrictedCapacityListClassNameWithoutInOutKeyword} DeepClone() => new(this);",
                $"object WodiLib.Sys.IDeepCloneable.DeepClone() => DeepClone();"
            );
        }
    }
}
