// ========================================
// Project Name : WodiLib.SourceGenerator
// File Name    : TwoDListGeneratorBase.BuildFixedLengthClassSource.cs
//
// MIT License Copyright(c) 2019 kameske
// see LICENSE file
// ========================================

using System.Linq;
using WodiLib.SourceGenerator.Core.SourceBuilder;
using WodiLib.SourceGenerator.ValueObject.Extensions;
using static WodiLib.SourceGenerator.Core.SourceBuilder.SourceConstants;

namespace WodiLib.SourceGenerator.Domain.Collection.Generation.Main.Common
{
    internal abstract partial class TwoDListGeneratorBase
    {
        private static SourceFormatTargetBlock BuildFixedLengthClassSource(ModelInformation modelInfo)
        {
            return SourceTextFormatter.Format(
                "",
                // -----
                // class start
                new[]
                {
                    $"/// <summary>",
                    $"/// {__}{modelInfo.Description}",
                    $"/// </summary>",
                    $"{modelInfo.Accessibility} {modelInfo.AbstractKeyword}partial class {modelInfo.FixedLengthListInfo.FixedLengthListClassName} : {modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword},",
                    $"{__}WodiLib.Sys.IDeepCloneable<{modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword}>",
                    $"{{",
                },
                // Properties
                BuildFixedLengthListPropertiesSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                BuildFixedLengthClassSettingsInterfaceImplementsSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // Constructors
                BuildFixedLengthListConstructorSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // Methods
                BuildFixedLengthListMethodsSource(modelInfo),
                SourceFormatTargetBlock.Empty,
                // DeepClone
                BuildFixedLengthListDeepCloneSource(modelInfo),
                // class end
                new[]
                {
                    $"}}",
                }
            );
        }

        private static SourceFormatTargetBlock BuildFixedLengthListPropertiesSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                __,
                $"/// <summary>",
                $"/// {__}{modelInfo.RowLogicalName}インデクサによるアクセス",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <returns>指定した{modelInfo.RowLogicalName}インデックスの{modelInfo.RowLogicalName}要素（長さ固定型）</returns>",
                $"/// <exception cref=\"ArgumentNullException\"><see langword=\"null\"/> をセットしようとした場合。</exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"public new {modelInfo.FixedLengthRowType} this[int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index]",
                $"{{",
                $"{__}get => Get{modelInfo.RowPhysicalName}( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"{__}set => Set{modelInfo.RowPhysicalName}( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, value);",
                $"}}",
                $"",
                $"/// <summary>",
                $"/// {__}{modelInfo.CellLogicalName}インデクサによるアクセス",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <returns>指定した{modelInfo.RowLogicalName}・{modelInfo.ColumnLogicalName}インデックスの{modelInfo.CellLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\"><see langword=\"null\"/> をセットしようとした場合。</exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>, <paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"public new {modelInfo.ElementType} this[int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index]",
                $"{{",
                $"{__}get => Get{modelInfo.CellPhysicalName}( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"{__}set => Set{modelInfo.CellPhysicalName}( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, value);",
                $"}}",
                $"",
                $"/// <summary>すべての編集可能{modelInfo.RowLogicalName}型要素</summary>",
                $"public new {modelInfo.FixedLengthRowType}[] Editable{modelInfo.RowPhysicalName}s => Table.EditableRows;"
            );
        }

        private static SourceFormatTargetBlock BuildFixedLengthClassSettingsInterfaceImplementsSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                modelInfo.Members.FixedLengthListProperties.SelectMany(p => p.ImplementationCode).ToArray()
            );
        }

        private static SourceFormatTargetBlock BuildFixedLengthListConstructorSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                $"public {modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword}({modelInfo.SettingsInterfaceInfo.SettingsInterfaceNameWithoutIOKeyword} settings) : base(settings) {{ }}",
                $"",
                $"private protected {modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword}({modelInfo.SettingsInterfaceInfo.SettingsInterfaceNameWithoutIOKeyword} settings, SimpleList<{modelInfo.RowType}> itemsImpl) : base(settings, itemsImpl) {{ }}",
                $"",
                modelInfo.Members.FixedLengthListConstructors.SelectMany(p => p.ImplementationCode).ToArray()
            );
        }

        private static SourceFormatTargetBlock BuildFixedLengthListMethodsSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                $"{__}",
                modelInfo.Members.FixedLengthListMethods.SelectMany(p => p.ImplementationCode).ToArray(),
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.RowPhysicalName}\"/>",
                $"public new {modelInfo.FixedLengthRowType} Get{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index) => Table.GetRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.RowPhysicalName}Range\"/>",
                $"public new IEnumerable<{modelInfo.FixedLengthRowType}> Get{modelInfo.RowPhysicalName}Range(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.GetRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの{modelInfo.RowLogicalName}要素を更新する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] 更新{modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">更新{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>セットした{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.RowLogicalName}要素を編集しようとした場合。",
                $"/// </exception>",
                $"public {modelInfo.FixedLengthRowType} Set{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.SetRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの連続した{modelInfo.RowLogicalName}要素を更新する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] 更新開始{modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">更新{modelInfo.RowLogicalName}要素</param>",
                $"/// <returns>セットした{modelInfo.RowLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.RowLogicalName}要素を編集しようとした場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Set{modelInfo.RowPhysicalName}Range(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.SetRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスにある項目をコレクション内の新しい場所へ移動する。",
                $"/// </summary>",
                $"/// <param name=\"old{modelInfo.RowPhysicalName}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] 移動する{modelInfo.RowLogicalName}のインデックス</param>",
                $"/// <param name=\"new{modelInfo.RowPhysicalName}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] 移動先の{modelInfo.RowLogicalName}インデックス</param>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}自身の{modelInfo.RowLogicalName}数が0の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"old{modelInfo.RowPhysicalName}Index\"/>, <paramref name=\"new{modelInfo.RowPhysicalName}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public void Move{modelInfo.RowPhysicalName}(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index) => Table.MoveRow(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.RowLogicalName}インデックスから始まる連続した項目をコレクション内の新しい場所へ移動する。",
                $"/// </summary>",
                $"/// <param name=\"old{modelInfo.RowPhysicalName}Index\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)]",
                $"/// {__}移動する{modelInfo.RowLogicalName}のインデックス開始位置",
                $"/// </param>",
                $"/// <param name=\"new{modelInfo.RowPhysicalName}Index\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)]",
                $"/// {__}移動先の{modelInfo.RowLogicalName}インデックス開始位置",
                $"/// </param>",
                $"/// <param name=\"count\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>)]",
                $"/// {__}移動させる{modelInfo.RowLogicalName}数",
                $"/// </param>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}自身の{modelInfo.RowLogicalName}数が0の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"old{modelInfo.RowPhysicalName}Index\"/>, <paramref name=\"new{modelInfo.RowPhysicalName}Index\"/>, <paramref name=\"count\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">有効な範囲外の{modelInfo.RowLogicalName}要素を移動しようとした場合。</exception>",
                $"public void Move{modelInfo.RowPhysicalName}Range(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index, int count)",
                $"{__}=> Table.MoveRowRange(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index, count);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.ColumnPhysicalName}\"/>",
                $"public new IEnumerable<{modelInfo.ElementType}> Get{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.GetColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.ColumnPhysicalName}Range\"/>",
                $"public new IEnumerable<IEnumerable<{modelInfo.ElementType}>> Get{modelInfo.ColumnPhysicalName}Range(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.GetColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの{modelInfo.ColumnLogicalName}要素を更新する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] 更新{modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">更新{modelInfo.ColumnLogicalName}要素</param>",
                $"/// <returns>セットした{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.ColumnLogicalName}要素を編集しようとした場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.ElementType}> Set{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.ElementSettingsType}> settings)",
                $"{__}=> Table.SetColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの連続した{modelInfo.ColumnLogicalName}要素を更新する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] 更新開始{modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">更新{modelInfo.ColumnLogicalName}要素（外側のIEnumerableが{modelInfo.ColumnLogicalName}、内側のIEnumerableが各{modelInfo.ColumnLogicalName}の{modelInfo.RowLogicalName}要素）</param>",
                $"/// <returns>セットした{modelInfo.ColumnLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.ColumnLogicalName}要素を編集しようとした場合。",
                $"/// </exception>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Set{modelInfo.ColumnPhysicalName}Range(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.SetColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスにある項目をコレクション内の新しい場所へ移動する。",
                $"/// </summary>",
                $"/// <param name=\"old{modelInfo.ColumnPhysicalName}Index\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)]",
                $"/// {__}移動する{modelInfo.ColumnLogicalName}のインデックス",
                $"/// </param>",
                $"/// <param name=\"new{modelInfo.ColumnPhysicalName}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] 移動先の{modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}自身の{modelInfo.ColumnLogicalName}数が0の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"old{modelInfo.ColumnPhysicalName}Index\"/>, <paramref name=\"new{modelInfo.ColumnPhysicalName}Index\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"public void Move{modelInfo.ColumnPhysicalName}(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index)",
                $"{__}=> Table.MoveColumn(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}指定した{modelInfo.ColumnLogicalName}インデックスから始まる連続した項目をコレクション内の新しい場所へ移動する。",
                $"/// </summary>",
                $"/// <param name=\"old{modelInfo.ColumnPhysicalName}Index\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)]",
                $"/// {__}移動する{modelInfo.ColumnLogicalName}のインデックス開始位置",
                $"/// </param>",
                $"/// <param name=\"new{modelInfo.ColumnPhysicalName}Index\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)]",
                $"/// {__}移動先の{modelInfo.ColumnLogicalName}インデックス開始位置",
                $"/// </param>",
                $"/// <param name=\"count\">",
                $"/// {__}[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/>)]",
                $"/// {__}移動させる{modelInfo.ColumnLogicalName}数",
                $"/// </param>",
                $"/// <exception cref=\"InvalidOperationException\">",
                $"/// {__}自身の{modelInfo.ColumnLogicalName}数が0の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\">",
                $"/// {__}<paramref name=\"old{modelInfo.ColumnPhysicalName}Index\"/>, <paramref name=\"new{modelInfo.ColumnPhysicalName}Index\"/>, <paramref name=\"count\"/> が指定範囲外の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">有効な範囲外の{modelInfo.ColumnLogicalName}要素を移動しようとした場合。</exception>",
                $"public void Move{modelInfo.ColumnPhysicalName}Range(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index, int count)",
                $"{__}=> Table.MoveColumnRange(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index, count);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.CellPhysicalName}\"/>",
                $"public new {modelInfo.ElementType} Get{modelInfo.CellPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.GetCell( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}二次元リストの{modelInfo.CellLogicalName}要素を更新する。",
                $"/// </summary>",
                $"/// <param name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/> - 1)] {modelInfo.RowLogicalName}インデックス</param>",
                $"/// <param name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\">[Range(0, <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> - 1)] {modelInfo.ColumnLogicalName}インデックス</param>",
                $"/// <param name=\"settings\">更新{modelInfo.CellLogicalName}要素</param>",
                $"/// <returns>セットした{modelInfo.CellLogicalName}要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentOutOfRangeException\"><paramref name=\"{modelInfo.RowPhysicalName.ToLowerFirstChar()}Index\"/>, <paramref name=\"{modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index\"/>が指定範囲外の場合。</exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}有効な範囲外の{modelInfo.CellLogicalName}要素を編集しようとした場合。",
                $"/// </exception>",
                $"public {modelInfo.ElementType} Set{modelInfo.CellPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ElementSettingsType} settings)",
                $"{__}=> Table.SetCell( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}要素を与えられた内容で一新する。",
                $"/// </summary>",
                $"/// <param name=\"settings\">二次元リストに詰め直す要素</param>",
                $"/// <returns>新たに二次元リストに詰め直した要素</returns>",
                $"/// <exception cref=\"ArgumentNullException\">",
                $"/// {__}<paramref name=\"settings\"/> が <see langword=\"null\"/> の場合、",
                $"/// {__}または <paramref name=\"settings\"/> に <see langword=\"null\"/> 要素が含まれる場合。",
                $"/// </exception>",
                $"/// <exception cref=\"ArgumentException\">",
                $"/// {__}<paramref name=\"settings\"/> の{modelInfo.RowLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.RowPhysicalName}Count\"/>、",
                $"/// {__}{modelInfo.ColumnLogicalName}数が <see cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.{modelInfo.ColumnPhysicalName}\"/> と異なる場合。",
                $"/// </exception>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Reset(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.Reset(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}要素をデフォルト値で一新する。",
                $"/// </summary>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Reset() => Table.Reset();",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateSet{modelInfo.RowPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.RowSettingsType} settings)",
                $"{__}=> Table.ValidateSetRow( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.RowPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.RowPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateSet{modelInfo.RowPhysicalName}Range(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.RowSettingsType}> settings)",
                $"{__}=> Table.ValidateSetRowRange( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateSet{modelInfo.ColumnPhysicalName}(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<{modelInfo.ElementSettingsType}> settings)",
                $"{__}=> Table.ValidateSetColumn({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.ColumnPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.ColumnPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateSet{modelInfo.ColumnPhysicalName}Range(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings)",
                $"{__}=> Table.ValidateSetColumnRange({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.CellPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.CellPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateSet{modelInfo.CellPhysicalName}(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ElementSettingsType} settings)",
                $"{__}=> Table.ValidateSetCell( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.RowPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.RowPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateMove{modelInfo.RowPhysicalName}(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index)",
                $"{__}=> Table.ValidateMoveRow(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.RowPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.RowPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateMove{modelInfo.RowPhysicalName}Range(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index, int count)",
                $"{__}=> Table.ValidateMoveRowRange(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.ColumnPhysicalName}\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.ColumnPhysicalName}\" path=\"param|exception\"/>",
                $"public void ValidateMove{modelInfo.ColumnPhysicalName}(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index)",
                $"{__}=> Table.ValidateMoveColumn(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.ColumnPhysicalName}Range\"/> メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.ColumnPhysicalName}Range\" path=\"param|exception\"/>",
                $"public void ValidateMove{modelInfo.ColumnPhysicalName}Range(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index, int count)",
                $"{__}=> Table.ValidateMoveColumnRange(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see",
                $"/// {__}{__}cref=\"Reset(System.Collections.Generic.IEnumerable{{{modelInfo.RowSettingsType}}})\"/>",
                $"/// {__}メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc",
                $"/// {__}cref=\"Reset(System.Collections.Generic.IEnumerable{{{modelInfo.RowSettingsType}}})\"",
                $"/// {__}path=\"param|exception\"/>",
                $"public void ValidateReset(IEnumerable<{modelInfo.RowSettingsType}> settings)",
                $"{__}=> Table.ValidateReset(settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see",
                $"/// {__}{__}cref=\"Reset()\"/>",
                $"/// {__}メソッドの検証処理。",
                $"/// </summary>",
                $"/// <inheritdoc",
                $"/// {__}cref=\"Reset()\"",
                $"/// {__}path=\"param|exception\"/>",
                $"public void ValidateReset() => Table.ValidateReset();",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.RowPhysicalName}Internal\"/>",
                $"public new {modelInfo.FixedLengthRowType} Get{modelInfo.RowPhysicalName}Internal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index) => Table.GetRowInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.RowPhysicalName}RangeInternal\"/>",
                $"public new IEnumerable<{modelInfo.FixedLengthRowType}> Get{modelInfo.RowPhysicalName}RangeInternal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.GetRowRangeInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.ColumnPhysicalName}Internal\"/>",
                $"public new IEnumerable<{modelInfo.ElementType}> Get{modelInfo.ColumnPhysicalName}Internal(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index) => Table.GetColumnInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.ColumnPhysicalName}RangeInternal\"/>",
                $"public new IEnumerable<IEnumerable<{modelInfo.ElementType}>> Get{modelInfo.ColumnPhysicalName}RangeInternal(int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, int count)",
                $"{__}=> Table.GetColumnRangeInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, count);",
                $"",
                $"/// <inheritdoc cref=\"{modelInfo.ReadOnlyListInfo.ReadOnlyListClassNameWithoutInOutKeyword}.Get{modelInfo.CellPhysicalName}Internal\"/>",
                $"public new {modelInfo.ElementType} Get{modelInfo.CellPhysicalName}Internal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index)",
                $"{__}=> Table.GetCellInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.RowPhysicalName}\" path=\"param\"/>",
                $"public {modelInfo.FixedLengthRowType} Set{modelInfo.RowPhysicalName}Internal(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}{modelInfo.RowSettingsType} settings",
                $") => Table.SetRowInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.RowPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.RowPhysicalName}Range\" path=\"param\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> Set{modelInfo.RowPhysicalName}RangeInternal(",
                $"{__}int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.SetRowRangeInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.ColumnPhysicalName}\" path=\"param\"/>",
                $"public IEnumerable<{modelInfo.ElementType}> Set{modelInfo.ColumnPhysicalName}Internal(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<{modelInfo.ElementSettingsType}> settings",
                $") => Table.SetColumnInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.ColumnPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.ColumnPhysicalName}Range\" path=\"param\"/>",
                $"public IEnumerable<IEnumerable<{modelInfo.ElementType}>> Set{modelInfo.ColumnPhysicalName}RangeInternal(",
                $"{__}int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index,",
                $"{__}IEnumerable<IEnumerable<{modelInfo.ElementSettingsType}>> settings",
                $") => Table.SetColumnRangeInternal({modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Set{modelInfo.CellPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Set{modelInfo.CellPhysicalName}\" path=\"param\"/>",
                $"public {modelInfo.ElementType} Set{modelInfo.CellPhysicalName}Internal(int {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, int {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ElementSettingsType} settings)",
                $"{__}=> Table.SetCellInternal( {modelInfo.RowPhysicalName.ToLowerFirstChar()}Index, {modelInfo.ColumnPhysicalName.ToLowerFirstChar()}Index, settings);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Mov{modelInfo.RowPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.RowPhysicalName}\" path=\"param\"/>",
                $"public void Move{modelInfo.RowPhysicalName}Internal(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index)",
                $"{__}=> Table.MoveRowInternal(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.RowPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.RowPhysicalName}Range\" path=\"param\"/>",
                $"public void Move{modelInfo.RowPhysicalName}RangeInternal(int old{modelInfo.RowPhysicalName}Index, int new{modelInfo.RowPhysicalName}Index, int count)",
                $"{__}=> Table.MoveRowRangeInternal(old{modelInfo.RowPhysicalName}Index, new{modelInfo.RowPhysicalName}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.ColumnPhysicalName}\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.ColumnPhysicalName}\" path=\"param\"/>",
                $"public void Move{modelInfo.ColumnPhysicalName}Internal(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index)",
                $"{__}=> Table.MoveColumnInternal(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index);",
                $"",
                $"/// <summary>",
                $"/// {__}<see cref=\"Move{modelInfo.ColumnPhysicalName}Range\"/> メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc cref=\"Move{modelInfo.ColumnPhysicalName}Range\" path=\"param\"/>",
                $"public void Move{modelInfo.ColumnPhysicalName}RangeInternal(int old{modelInfo.ColumnPhysicalName}Index, int new{modelInfo.ColumnPhysicalName}Index, int count)",
                $"{__}=> Table.MoveColumnRangeInternal(old{modelInfo.ColumnPhysicalName}Index, new{modelInfo.ColumnPhysicalName}Index, count);",
                $"",
                $"/// <summary>",
                $"/// {__}<see",
                $"/// {__}{__}cref=\"Reset(System.Collections.Generic.IEnumerable{{{modelInfo.RowSettingsType}}})\"/>",
                $"/// {__}メソッド処理中核。",
                $"/// </summary>",
                $"/// <inheritdoc",
                $"/// {__}cref=\"Reset(System.Collections.Generic.IEnumerable{{{modelInfo.RowSettingsType}}})\"",
                $"/// {__}path=\"param\"/>",
                $"public IEnumerable<{modelInfo.FixedLengthRowType}> ResetInternal(",
                $"{__}IEnumerable<{modelInfo.RowSettingsType}> settings",
                $") => Table.ResetInternal(settings);"
            );
        }

        private static SourceFormatTargetBlock BuildFixedLengthListDeepCloneSource(
            ModelInformation modelInfo
        )
        {
            return SourceTextFormatter.Format(
                __,
                $"/// <inheritdoc/>",
                $"public new {modelInfo.FixedLengthListInfo.FixedLengthListClassNameWithoutInOutKeyword} DeepClone() => new(this);",
                $"object IDeepCloneable.DeepClone() => DeepClone();"
            );
        }
    }
}
